root = "."
tmp_dir = "tmp"

[build]
  cmd = "make --no-print-directory build-air"
  bin = "./tmp/main"
  full_bin = "ENV=dev ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = [".tools", "coverage", "tmp", "vendor", "bin"]
